### ISSUE TITLE
vim-common package installed?

### ISSUE THREAD

**Issue by brycekahle** [spark/buildpack-gcc#1]
Is there a reason the `vim-common` package is installed?

https://github.com/spark/buildpack-gcc/blob/56eef6e2d7c004067ef317b00e3773fac537c738/Dockerfile#L9

**Comment by suda** [comment]
Yes and a very "Ubuntu-ish" one: Firmware makefile [uses `xxd`](https://github.com/spark/firmware/search?utf8=%E2%9C%93&q=xxd) which in Ubuntu happens to be in  [`vim-common` package](http://packages.ubuntu.com/xenial/i386/vim-common/filelist) 😁
